import type { StateTemplates } from "./types";

export const GA: StateTemplates = {
	name: "Georgia",
	statute: "Georgia Code § 44-14-366 (Statutory 2021-2026)",
	lastVerified: "Feb 15, 2026",
	sourceUrl:
		"https://law.justia.com/codes/georgia/2022/title-44/chapter-14/article-8/part-2/section-44-14-366/",
	baseFontSize: 12,
	forms: {
		conditional_progress: {
			title:
				"WAIVER AND RELEASE OF LIEN AND PAYMENT BOND RIGHTS UPON INTERIM PAYMENT",
			notice:
				"NOTICE: WHEN YOU EXECUTE AND SUBMIT THIS DOCUMENT, YOU SHALL BE CONCLUSIVELY DEEMED TO HAVE BEEN PAID IN FULL THE AMOUNT STATED ABOVE, EVEN IF YOU HAVE NOT ACTUALLY RECEIVED SUCH PAYMENT, 90 DAYS AFTER THE DATE STATED ABOVE UNLESS YOU FILE EITHER AN AFFIDAVIT OF NONPAYMENT OR A CLAIM OF LIEN PRIOR TO THE EXPIRATION OF SUCH 90 DAY PERIOD.",
			noticeStyle: {
				fontSize: 12,
				isBold: true,
				isAllCaps: true,
			},
			body: "UPON THE RECEIPT OF THE SUM OF ${{paymentAmount}}, THE MECHANIC AND/OR MATERIALMAN WAIVES AND RELEASES ANY AND ALL LIENS OR CLAIMS OF LIENS IT HAS UPON THE FOREGOING DESCRIBED PROPERTY OR ANY RIGHTS AGAINST ANY LABOR AND/OR MATERIAL BOND THROUGH THE DATE OF {{throughDate}} AND EXCEPTING THOSE RIGHTS AND LIENS THAT THE MECHANIC AND/OR MATERIALMAN MIGHT HAVE IN ANY RETAINED AMOUNTS, ON ACCOUNT OF LABOR OR MATERIALS, OR BOTH, FURNISHED BY THE UNDERSIGNED TO OR ON ACCOUNT OF SAID CONTRACTOR FOR SAID BUILDING OR PREMISES.",
			fields: ["paymentAmount", "throughDate"],
		},
		unconditional_progress: {
			title:
				"WAIVER AND RELEASE OF LIEN AND PAYMENT BOND RIGHTS UPON INTERIM PAYMENT",
			notice:
				"NOTICE: THIS FORM IS UNCONDITIONAL AFTER 90 DAYS UNLESS AN AFFIDAVIT OF NONPAYMENT IS FILED.",
			noticeStyle: {
				fontSize: 12,
				isBold: true,
				isAllCaps: true,
			},
			body: "UPON THE RECEIPT OF THE SUM OF ${{paymentAmount}}, THE MECHANIC AND/OR MATERIALMAN WAIVES AND RELEASES ANY AND ALL LIENS OR CLAIMS OF LIENS IT HAS UPON THE FOREGOING DESCRIBED PROPERTY OR ANY RIGHTS AGAINST ANY LABOR AND/OR MATERIAL BOND THROUGH THE DATE OF {{throughDate}}.",
			fields: ["paymentAmount", "throughDate"],
		},
		conditional_final: {
			title:
				"WAIVER AND RELEASE OF LIEN AND PAYMENT BOND RIGHTS UPON FINAL PAYMENT",
			notice:
				"NOTICE: WHEN YOU EXECUTE AND SUBMIT THIS DOCUMENT, YOU SHALL BE CONCLUSIVELY DEEMED TO HAVE BEEN PAID IN FULL THE AMOUNT STATED ABOVE, EVEN IF YOU HAVE NOT ACTUALLY RECEIVED SUCH PAYMENT, 90 DAYS AFTER THE DATE STATED ABOVE UNLESS YOU FILE EITHER AN AFFIDAVIT OF NONPAYMENT OR A CLAIM OF LIEN PRIOR TO THE EXPIRATION OF SUCH 90 DAY PERIOD.",
			noticeStyle: {
				fontSize: 12,
				isBold: true,
				isAllCaps: true,
			},
			body: "UPON THE RECEIPT OF THE SUM OF ${{paymentAmount}}, THE MECHANIC AND/OR MATERIALMAN WAIVES AND RELEASES ANY AND ALL LIENS OR CLAIMS OF LIENS IT HAS UPON THE FOREGOING DESCRIBED PROPERTY OR ANY RIGHTS AGAINST ANY LABOR AND/OR MATERIAL BOND ON ACCOUNT OF LABOR OR MATERIALS, OR BOTH, FURNISHED BY THE UNDERSIGNED TO OR ON ACCOUNT OF SAID CONTRACTOR FOR SAID PROPERTY.",
			fields: ["paymentAmount"],
		},
		unconditional_final: {
			title:
				"WAIVER AND RELEASE OF LIEN AND PAYMENT BOND RIGHTS UPON FINAL PAYMENT",
			notice:
				"NOTICE: THIS FORM IS UNCONDITIONAL AND STATES THAT YOU HAVE BEEN PAID FOR GIVING UP THOSE RIGHTS.",
			noticeStyle: {
				fontSize: 12,
				isBold: true,
				isAllCaps: true,
			},
			body: "The undersigned has been paid in full the amount of ${{paymentAmount}} for all labor, services, equipment, or material provided to the contractor on the job for the property located at {{projectAddress}}.",
			fields: ["paymentAmount", "projectAddress"],
		},
	},
};
